
server:
  port: 9191
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: system-server
        uri: http://localhost:8080/
        predicates:
        - Path=/system/**
      - id: guard-server
        uri: http://localhost:8081/
        predicates:
        - Path=/guard/**
          
          
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/